import os
import sys
import subprocess
import tempfile
from pathlib import Path
import re

def _help_text_for(subcmd: str) -> str:
    proc = subprocess.run(
        [sys.executable, "-m", "reposmith.main", subcmd, "--help"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    )
    return proc.stdout or ""

def _is_flag_supported(help_text: str, flag: str) -> bool:
    pat = r"(?:^|\s)" + re.escape(flag) + r"(?:\s|,|$)"
    return re.search(pat, help_text) is not None

class TestCLISmokeWithCI:
    def _run(self, args, cwd: Path):
        return subprocess.run(
            [sys.executable, "-m", "reposmith.main"] + args,
            cwd=cwd,
            check=True,
        )

    def test_ci_adaptive(self):
        """
        لو CLI بدعّم --with-ci/--ci-python: جرّبه عبر CLI وتأكد من إنشاء workflow.
        لو ما بدعّم: اختبر الدالة الداخلية ensure_github_actions_workflow مباشرة (إن وُجدت).
        """
        with tempfile.TemporaryDirectory() as td:
            proj = Path(td) / "proj"
            proj.mkdir(parents=True, exist_ok=True)

            help_text = _help_text_for("init")
            workflows_dir = proj / ".github" / "workflows"
            ci_file = workflows_dir / "ci.yml"

            if _is_flag_supported(help_text, "--with-ci"):
                args = ["init", "--with-ci"]
                if _is_flag_supported(help_text, "--ci-python"):
                    args += ["--ci-python", "3.13"]
                # اختياري: لو بدعّم --entry خلّيه ينشئ ملف
                if _is_flag_supported(help_text, "--entry"):
                    args += ["--entry", "run.py"]
                self._run(args, cwd=proj)
                assert ci_file.exists(), "Expected CI workflow to be generated via CLI."
            else:
                # لا يوجد علم --with-ci؛ جرّب الدالة الداخلية إن وُجدت
                try:
                    from reposmith.ci_utils import ensure_github_actions_workflow
                except Exception:
                    # لا ميزات CI متاحة — فقط تأكد من أن CLI init لا ينهار
                    self._run(["init"], cwd=proj)
                    return

                # استدعاء مباشر للدالة الداخلية
                ensure_github_actions_workflow(proj, python_version="3.12")
                assert ci_file.exists(), "Expected CI workflow to be generated by ensure_github_actions_workflow()."
