name: CI

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "*.md"
      - "docs/**"
      - ".github/ISSUE_TEMPLATE/**"
  push:
    branches: [ "main" ]
    tags:
      - "v*"
    paths-ignore:
      - "*.md"
      - "docs/**"
      - ".github/ISSUE_TEMPLATE/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.13"]

    # Ignore draft PRs
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install uv (fast Python package manager)
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade uv

      - name: Install project (editable) + test deps
        run: |
          if [ -f pyproject.toml ] || [ -f setup.cfg ] || [ -f setup.py ]; then
            # prefer uv (fast); fallback to pip if needed
            if uv pip install -e .; then
              uv pip install pytest pytest-cov
            else
              pip install -e .
              pip install pytest pytest-cov
            fi
          else
            # if repo has only tests or a subset
            uv pip install pytest pytest-cov || pip install pytest pytest-cov
          fi

      - name: Run tests with coverage
        run: |
          pytest -q -ra --cov=. --cov-report=term-missing
        env:
          PYTHONUTF8: "1"

      - name: Upload coverage (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./.coverage*
          if-no-files-found: ignore

  build:
    name: Build package
    runs-on: ubuntu-latest
    needs: test
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') }}
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - name: Build sdist/wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
