name: Run Python Tests

on:
  push:
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }} • Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.12", "3.13"]

    env:
      PYTHONUTF8: "1"
      PYTHONIOENCODING: "utf-8"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Install project and test dependencies (system mode)
        run: |
          uv pip install --system -e ".[dev]" || uv pip install --system -e .
          uv pip install --system pytest pytest-cov

      - name: Run tests (no emoji)
        env:
          REPOSMITH_NO_EMOJI: "1"
        run: pytest -q -ra --maxfail=1 --cov=. --cov-report=term-missing

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./.coverage*
          if-no-files-found: ignore
